# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use a Node.js image
FROM node:18-alpine AS builder

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package.json ./

# Install dependencies
RUN npm install --ignore-scripts

# Copy the rest of the application code
COPY . .

# Build the application
RUN npm run build

# Use a separate stage for the release
FROM node:18-alpine AS release

# Set the working directory
WORKDIR /app

# Copy only the necessary files from the builder stage
COPY --from=builder /app/dist /app/dist
COPY --from=builder /app/package.json /app/package.json
COPY --from=builder /app/pgpt.env.json.example /app/pgpt.env.json

# Install only production dependencies
RUN npm ci --omit=dev

# Set the environment to production
ENV NODE_ENV=production

# Expose the port specified in the configuration
EXPOSE 5000

# Run the server
CMD ["node", "dist/index.js"]
